### PR TITLE
- add --phased_proximal_variants option to generate_protein_fasta.py

### PR DESCRIPTION
**Pull request by riederd**
It would be useful to consider also the proximal variants in the tool generate_protein_fasta.
Would you please consider to review and hopefully add the changes I made to implement this feature.
In addition I added the positional argument sample_name in order to enable multi sample vcfs.

Thanks so much.
 Dietmar

### CODE REVIEW

**Comment by susannasiebert** [comment]
This was already implemented in https://github.com/griffithlab/pVACtools/pull/531 and merged into staging (which is where we merge pull requests for new feature additions). I will update the base branch of this PR to staging and compare if there are any additional changes made in this PR that could be useful to be merged in.

**Comment by susannasiebert** [comment]
On a  quick glance it looks like you accidentally overwrote the `tools/pvacfuse/generate_protein_fasta.py` file with your version of the `pvacseq` file that has your changes (instead of applying the changes to `tools/pvacseq/generate_protein_fasta.py`). Would you be able to apply your changes to the correct file? It might be useful to start with the version of the file in the staging branch, to see if you there are any additional changes needed.

**Comment by riederd** [comment]
Ok, sorry, you are right. I'll check

**Comment by riederd** [comment]
I'll close the request. And see if the code in staging is fine for me.

**Pull request closed without merging**
