### PR TITLE
Pvacvector visualization

### PR DESCRIPTION
**Pull request by susannasiebert**
The package to run `covert` is difficult to set up. Leaving the vaccine vector graphic as a `.ps` file seems sufficient.

This also increases the canvas width to 1200 pixels which is needed for the longer epitopes names.

### CODE REVIEW

**Comment by chrisamiller** [comment]
Thinking ahead, will that ps file display in browser? (assuming that we'll wrap this into the web interface eventually)

**Comment by susannasiebert** [comment]
Good point. It does not display. I will work on an alternative. For now I think this is a good stop-gap measure to get this running more reliably.

**Comment by chrisamiller** [comment]
Yeah, I have no objection to the change in general! I just know that lots of people will ultimately want a jpg/gif/png that's less complicated to view

**Comment by susannasiebert** [comment]
Good new everyone! I found a python module to convert images without having to make a system call to a command line tool. I pushed a commit to use that instead.

**Comment by chrisamiller** [comment]
Nice!  +1

**Pull request merged**
