### PR TITLE
Add percentile ranks to the reports

### PR DESCRIPTION
**Pull request by susannasiebert**
This is the first PR to add the percentile rank to the all_epitopes.tsv and filtered.tsv output files (#454).

### CODE REVIEW

**Comment by chrisamiller** [comment]
+1

**Comment by MatDal** [comment]
Hello,
using pvacbind on the "percentile" branch all the output percentile values for MHC_II are NA using length 15.

**Comment by susannasiebert** [comment]
@MatDal which prediction algorithm(s) are you using?

**Comment by MatDal** [comment]
NetMHCIIpan  NNalign and SMMalign

**Comment by susannasiebert** [comment]
@MatDal we had a bug in the iedb output parsing logic. I have fixed it and pushed a new commit to this branch with the change.

**Comment by susannasiebert** [comment]
FYI, I rebased and cleaned up this branch to remove merge commits and merge conflicts. @chrisamiller do you mind re-reviewing when you get a chance?

**Comment by MatDal** [comment]
Thanks!!!

**Comment by MatDal** [comment]
I have the same problem also after the update.

**Comment by susannasiebert** [comment]
@MatDal confirmed via email that the latest update works. I'll merge this PR.

**Pull request merged**
